name: Challenge5
on:
    workflow_dispatch:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Login to Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS_CH }}
        - name: Deploy Bicep Template
          uses: azure/arm-deploy@v1
          with:
            subscriptionId: "16fbc8d0-52d4-49e2-9d80-887dd122d97e"
            resource-group: ${{ vars.RG_CH }}
            template: ./InfrastructureAsCode/main.bicep