name: Challenge4
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
  workflow_dispatch: 
  issues:
    types: [opened]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        run: echo Hello, world!
      - name: Step2
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Action from Marketplace
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: 'ship ship ship!'
          color: 'white'