 name: Azure ARM
 on: 
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      targetEnv: 
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Target Environment'
        # Default value if no value is explicitly provided
        default: 'dev'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
     
 jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:

        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ vars.AZURE_RG }}
          template: ./ARM-Templates/container-webapp-template.json
          parameters: webAppName=srsssdevops-${{inputs.targetEnv}}
          

        # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}
