name: Deploy_CB
run-name: ${{ github.actor }} is learning GitHub Actions
on:
   workflow_dispatch:
    inputs:
      environment:
       description: 'Environment to deploy to'
       required: true
       default: 'dev'
       options:
          - 'dev'
          - 'staging'
          - 'production'
        actions:
          - name: 'Deploy Azure Resource Manager (ARM) Template'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
                creds: ${{ secrets.AZURE_CREDENTIALS_CB }}
    - name: Deploy ARM Template
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ env.SUBSCRIPTIONID_CB }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_CB }}
        template: ./InfrastructureAsCode/main.bicep
        parameters: ./path/to/parameters.json