name: Run Azure Login
on:
    workflow_dispatch:
jobs:
  az-login-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.uma_service_principle_secret }}
      - name: Azure CLI
        run: |
          az account show
          az group list

      - name: Azure Deploy
        uses : azure/arm-deploy@v2
        with:
          resourceGroupName: ${{ secrets.uma_resource_grp }}
          template: Application/src/RazorPagesTestSample/main.bicep
          failOnStdErr: false