name: Run Azure Login
on:
    workflow_dispatch:
jobs:
  az-login-test:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.uma_service_principle_secret }}
      - name: Azure CLI
        run: |
          az account show
          az group list
