name: Challenge4
run-name: ${{ github.actor }} is learning GitHub Actions
on: [workflow_dispatch,push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job1 Step1
        run: echo Hello, Job1!
      - name: Job1 Step2
        run: |
          echo Add other actions to build.
  job2:
    runs-on: ubuntu-latest
    steps:
        - name: Job2 Step1
          run: echo Hello, Job2!
        - name: Job2 Step2
          run: |
            echo Add other job to build.
